### ISSUE TITLE
Can't use this on generic multi-node cluster.

### ISSUE THREAD

**Issue by hansbogert** [routernetes/routernetes-operator#1]
**Describe the bug**
(As documented though), the current operator implementation is not suitable for a (pre-existing) multi-node cluster.

- multiple dhcp servers are started, as the daemonset by default tries to run the pods on all nodes.
- further, the pods won't run as the PVC can't be fulfilled. In my case due to the inflexibility of not being able to specify a storageClass.

**To Reproduce**
Install the operator in a multi-node cluster

**Expected behavior**
Installs a single instance of the intended daemonset pods.

**Comment by loganmc10** [comment]
> the current operator implementation is not suitable for a (pre-existing) multi-node cluster

This is true, it's really only currently designed to work based on the validated install guide (https://github.com/routernetes/routernetes/wiki/Install-Guide).

I don't mind adding support for multi-node clusters, but I'm curious how you envision this working? The routing can really only be done on a single node, I could add an option to the CRD to specify a Node Selector so that the daemonset is only deployed on the node specified by the Node Selector

> further, the pods won't run as the PVC can't be fulfilled. In my case due to the inflexibility of not being able to specify a storageClass.

Yes I'll add this to my todo list (an option to specify a StorageClass, right now it only works if a default StorageClass is specified)

**Comment by hansbogert** [comment]
> This is true, it's really only currently designed to work based on the validated install guide (https://github.com/routernetes/routernetes/wiki/Install-Guide).

Yeah, totally aware of that, and acknowledged by the `"(As documented though)"` :), though this operator has quite the potential!

> I could add an option to the CRD to specify a Node Selector so that the daemonset is only deployed on the node specified by the Node Selector

That seems like the obvious thing idd.

**Comment by loganmc10** [comment]
I've completed this work and it is in the main branch (https://github.com/routernetes/routernetes-operator/commit/cd03f780154c2b1e1df76c6c3660a15b8a31a4b8). However, I'm currently blocked by a bug that prevents me from publishing updates on OperatorHub (https://github.com/operator-framework/operator-sdk/issues/5880). Once that is fixed, I'll upload a new version to OperatorHub

Here are the new fields in the spec:

```
spec:
  nodeSelectorLabels:
    kubernetes.io/hostname: myHost
```
```
spec:
  dhcp:
    storageClass: my-class
```

**Comment by hansbogert** [comment]
Awesome, looking forward to the updated operator!

**Comment by loganmc10** [comment]
Keep in mind that there are other requirements for the host. FirewallD and TuneD run in containers as part of the DaemonSet. In order for FirewallD and TuneD to communicate with the underlying host, there are some DBus and Polkit files that need to be present on the host.

Currently, those files aren't separated from the main firewalld/tuned packages, which means that what I do currently is install FirewallD and TuneD on the host, and then disable them:

https://github.com/routernetes/routernetes/blob/9f53012e0701e315f1cd1c64484d21ee89185704/installer/butane.yaml#L63-L67

NetworkManager also needs to be running on the host

**Comment by hansbogert** [comment]
I see; that's quite a deviation from the cloud-native concept. Was this something that can't be done otherwise, or just as a get-it-to-work-for-now solution?

**Comment by loganmc10** [comment]
I wouldn't say it goes against any cloud-native concept, it just isn't cloud-agnostic at the moment. Firewalling, NAT, and IP forwarding are functions performed by the Linux kernel. Given that all containers share the Linux kernel, it is inevitable that for a project like this, the container is going to need extra privileges and it's going to need to interact closely with the underlying system.

Having to modify the underlying host system isn't something that necessarily breaks any cloud-native concept. For instance, OpenShift has a MachineConfig k8s CRD that allows you to modify files on the host using the API, but I don't think there is anything that has been standardized in upstream k8s for this yet (maybe I'm wrong).

There is the potential to maybe use an Init Container to copy the necessary DBus and Polkit files onto the host, rather than count on the host already having them there. I might play around with it in the future, but for this initial release I was mostly assuming people would use the provided OS image.

**Comment by loganmc10** [comment]
Alright the new version of the operator has finally been published, it now supports a nodeSelector and a StorageClass selector
